- hosts: 127.0.0.1
  connection: local
  serial: 1
  gather_facts: false
  tasks:
  - name: Manage package installation
    ansible.builtin.apt:
      name:
      - python3
      - python3-git
      - python3-ansible-runner
      - python3-validators
      - python3-psutil
      - python3-distro
      - cron
      state: latest
      update_cache: true
  - name: Manage cron systemd service
    ansible.builtin.systemd:
      state: restarted
      name: cron
      enabled: true
